export const goalsCopyRu = {
  submenu: {
    search: 'Поиск',
    filters: 'Фильтры',
    roots: 'Корни',
    forge: 'Кузница',
  },
  left: {
    title: 'Навигатор',
    addGoal: '+ Цель',
    searchPlaceholder: 'Найти цель',
    noGoals: 'Пока нет целей в этом состоянии.',
  },
  stage: {
    hint: 'Сцена',
    resetView: 'Сброс вида (R)',
    focus: 'Фокус (F)',
    pickGoalHint: 'Выберите цель в списке или посадите новую.',
  },
  cockpit: {
    summary: 'Состояние',
    diagnosis: 'Что проседает',
    weakSpot: 'Слабое место',
    reason: 'Причина',
    nextStep: 'Что делать сейчас',
    selectHint: 'Выбери цель на сцене или в списке.',
    warnings: 'Предупреждение',
    missionWhyToggle: 'Почему',
    missionAccept: 'Принять',
    missionDefer: 'Отложить',
    missionComplete: 'Выполнено',
    missionSnoozed: 'Шаг отложен',
    missionReturn: 'Вернуть',
    missionNext: 'Следующий шаг',
    missionInWork: 'в работе',
    missionHasStep: 'есть шаг',
    missionDone: 'готово',
    missionEffect: 'Эффект',
    missionCost: 'Стоимость времени',
    missionNoData: 'Калибровка / чек-ин',
    keyBranches: 'Ключевые ветви',
  },
} as const
