export const goalsCopyRu = {
  submenu: {
    search: 'Поиск',
    filters: 'Фильтры',
    roots: 'Корни',
    forge: 'Кузница',
  },
  left: {
    title: 'Навигатор',
    addGoal: '+ Цель',
    searchPlaceholder: 'Найти цель',
    noGoals: 'Пока нет целей в этом состоянии.',
  },
  stage: {
    hint: 'Сцена',
    resetView: 'Сброс вида (R)',
    focus: 'Фокус (F)',
    pickGoalHint: 'Выберите цель в списке или посадите новую.',
  },
  cockpit: {
    summary: 'Состояние',
    selectedGoal: 'Выбранная цель',
    weakSpot: 'Слабое место',
    whyNow: 'Почему сейчас важно',
    nextStep: 'Следующий шаг',
    selectHint: 'Выбери цель на сцене или в списке.',
    warnings: 'Предупреждения',
    missionWhyToggle: 'Почему',
    missionDetails: 'Подробнее',
    missionAccept: 'Принять шаг',
    missionDone: 'Выполнено',
    missionDefer: 'Отложить',
    missionInWork: 'в работе',
    missionHasStep: 'есть шаг',
    missionEffect: 'Эффект',
    missionCost: 'Стоимость времени',
    missionNoData: 'Калибровка / чек-ин',
  },
} as const
